/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author emirb
 */
public class Interface extends javax.swing.JFrame {
Partie_Recherche jeu = new Partie_Recherche();
int[] tentative = {0, 0, 0, 0}; // case1 – case2 – case3 – case4
int nbTentatives = 0;
public Interface() {
    initComponents();
}
    
    /**
     * Creates new form Interface
     */
  
   
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel1_Texte_intro = new javax.swing.JLabel();
        jButton1_upcase1 = new javax.swing.JButton();
        jButton2_upcase2 = new javax.swing.JButton();
        jButton3_upcase3 = new javax.swing.JButton();
        jButton4_upcase4 = new javax.swing.JButton();
        jButton5_downcase1 = new javax.swing.JButton();
        jButton7_downcase3 = new javax.swing.JButton();
        jButton8_downcase4 = new javax.swing.JButton();
        jLabel2_case1 = new javax.swing.JLabel();
        jLabel3_case2 = new javax.swing.JLabel();
        jLabel4_case3 = new javax.swing.JLabel();
        jLabel5_case4 = new javax.swing.JLabel();
        jButton_TESTER = new javax.swing.JButton();
        jLabel6_tentatives = new javax.swing.JLabel();
        jLabel7_exact = new javax.swing.JLabel();
        jLabel8_hauts = new javax.swing.JLabel();
        jLabel9_bas = new javax.swing.JLabel();
        jLabel10_score = new javax.swing.JLabel();
        jButton1_recommencer = new javax.swing.JButton();
        jLabel2_afficherbon = new javax.swing.JLabel();
        jLabel3_afficherhauts = new javax.swing.JLabel();
        jLabel4_afficherbas = new javax.swing.JLabel();
        jLabel2_nbrdetentatives = new javax.swing.JLabel();
        jButton6_downcase2 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1_Texte_intro.setText("Trouver le bon code en moins de 5 tentatives");

        jButton1_upcase1.setText("/\\");
            jButton1_upcase1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1_upcase1ActionPerformed(evt);
                }
            });

            jButton2_upcase2.setText("/\\");
                jButton2_upcase2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton2_upcase2ActionPerformed(evt);
                    }
                });

                jButton3_upcase3.setText("/\\");
                    jButton3_upcase3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton3_upcase3ActionPerformed(evt);
                        }
                    });

                    jButton4_upcase4.setText("/\\");
                        jButton4_upcase4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton4_upcase4ActionPerformed(evt);
                            }
                        });

                        jButton5_downcase1.setText("\\/");
                        jButton5_downcase1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton5_downcase1ActionPerformed(evt);
                            }
                        });

                        jButton7_downcase3.setText("\\/");
                        jButton7_downcase3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton7_downcase3ActionPerformed(evt);
                            }
                        });

                        jButton8_downcase4.setText("\\/");
                        jButton8_downcase4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton8_downcase4ActionPerformed(evt);
                            }
                        });

                        jLabel2_case1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        jLabel2_case1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        jLabel2_case1.setText("0");
                        jLabel2_case1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        jLabel2_case1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                        jLabel2_case1.setVerifyInputWhenFocusTarget(false);

                        jLabel3_case2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        jLabel3_case2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        jLabel3_case2.setText("0");
                        jLabel3_case2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                        jLabel4_case3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        jLabel4_case3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        jLabel4_case3.setText("0");
                        jLabel4_case3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                        jLabel5_case4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                        jLabel5_case4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        jLabel5_case4.setText("0");
                        jLabel5_case4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                        jButton_TESTER.setText("TESTER");
                        jButton_TESTER.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton_TESTERActionPerformed(evt);
                            }
                        });

                        jLabel6_tentatives.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        jLabel6_tentatives.setText("Tentatives :");
                        jLabel6_tentatives.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                        jLabel7_exact.setText("Nombres de chiffres exactes : ");

                        jLabel8_hauts.setText("Nombres de chiffres hauts :");

                        jLabel9_bas.setText("Nombres de chiffres bas : ");

                        jLabel10_score.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                        jLabel10_score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        jLabel10_score.setText("/5");

                        jButton1_recommencer.setText("RECOMMENCER");
                        jButton1_recommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1_recommencerActionPerformed(evt);
                            }
                        });

                        jLabel2_afficherbon.setText("0");

                        jLabel3_afficherhauts.setText("0");

                        jLabel4_afficherbas.setText("0");

                        jLabel2_nbrdetentatives.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                        jLabel2_nbrdetentatives.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        jLabel2_nbrdetentatives.setText("0");

                        jButton6_downcase2.setText("\\/");
                        jButton6_downcase2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton6_downcase2ActionPerformed(evt);
                            }
                        });

                        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                        getContentPane().setLayout(layout);
                        layout.setHorizontalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8_hauts, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9_bas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4_afficherbas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel3_afficherhauts, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel7_exact, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2_afficherbon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jButton1_recommencer, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel2_nbrdetentatives, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10_score, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel6_tentatives, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton1_upcase1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2_case1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButton5_downcase1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton_TESTER, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButton6_downcase2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jButton7_downcase3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(jButton2_upcase2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addComponent(jButton3_upcase3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(jLabel3_case2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addComponent(jLabel4_case3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jButton4_upcase4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jButton8_downcase4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel5_case4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(36, 36, 36))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1_Texte_intro, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(45, 45, 45)))))
                                .addGap(23, 23, 23))
                        );
                        layout.setVerticalGroup(
                            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1_Texte_intro)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton7_downcase3)
                                            .addComponent(jButton8_downcase4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton_TESTER))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton1_upcase1)
                                            .addComponent(jButton2_upcase2)
                                            .addComponent(jButton3_upcase3)
                                            .addComponent(jButton4_upcase4))
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2_case1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3_case2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4_case3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5_case4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton5_downcase1)
                                            .addComponent(jButton6_downcase2))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7_exact)
                                            .addComponent(jLabel2_afficherbon))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8_hauts)
                                            .addComponent(jLabel3_afficherhauts))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9_bas)
                                            .addComponent(jLabel4_afficherbas))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1_recommencer)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6_tentatives)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10_score)
                                            .addComponent(jLabel2_nbrdetentatives, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addContainerGap())))
                        );

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void jButton_TESTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TESTERActionPerformed
 
    }//GEN-LAST:event_jButton_TESTERActionPerformed

    private void jButton1_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_recommencerActionPerformed
                                                   
  
      
    }//GEN-LAST:event_jButton1_recommencerActionPerformed

    private void jButton1_upcase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_upcase1ActionPerformed
       tentative[0] = (tentative[0] + 1) % 10;
    jLabel2_case1.setText("" + tentative[0]);
    }//GEN-LAST:event_jButton1_upcase1ActionPerformed

    private void jButton2_upcase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_upcase2ActionPerformed
     tentative[1] = (tentative[1] + 1) % 10;
    jLabel3_case2.setText("" + tentative[1]);
    }//GEN-LAST:event_jButton2_upcase2ActionPerformed

    private void jButton3_upcase3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_upcase3ActionPerformed
    tentative[2] = (tentative[2] + 1) % 10;
    jLabel4_case3.setText("" + tentative[2]);
    }//GEN-LAST:event_jButton3_upcase3ActionPerformed

    private void jButton4_upcase4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_upcase4ActionPerformed
    tentative[3] = (tentative[3] + 1) % 10;
    jLabel5_case4.setText("" + tentative[3]);
    }//GEN-LAST:event_jButton4_upcase4ActionPerformed

    private void jButton5_downcase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_downcase1ActionPerformed
       tentative[0] = (tentative[0] + 9) % 10;
    jLabel2_case1.setText("" + tentative[0]);
    }//GEN-LAST:event_jButton5_downcase1ActionPerformed

    private void jButton7_downcase3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7_downcase3ActionPerformed
    tentative[2] = (tentative[2] + 9) % 10;
    jLabel4_case3.setText("" + tentative[2]);
    }//GEN-LAST:event_jButton7_downcase3ActionPerformed

    private void jButton8_downcase4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8_downcase4ActionPerformed
     tentative[3] = (tentative[3] + 9) % 10;
    jLabel5_case4.setText("" + tentative[3]);
    }//GEN-LAST:event_jButton8_downcase4ActionPerformed

    private void jButton6_downcase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6_downcase2ActionPerformed
    tentative[1] = (tentative[1] + 9) % 10;
    jLabel3_case2.setText("" + tentative[1]);
    }//GEN-LAST:event_jButton6_downcase2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_recommencer;
    private javax.swing.JButton jButton1_upcase1;
    private javax.swing.JButton jButton2_upcase2;
    private javax.swing.JButton jButton3_upcase3;
    private javax.swing.JButton jButton4_upcase4;
    private javax.swing.JButton jButton5_downcase1;
    private javax.swing.JButton jButton6_downcase2;
    private javax.swing.JButton jButton7_downcase3;
    private javax.swing.JButton jButton8_downcase4;
    private javax.swing.JButton jButton_TESTER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10_score;
    private javax.swing.JLabel jLabel1_Texte_intro;
    private javax.swing.JLabel jLabel2_afficherbon;
    private javax.swing.JLabel jLabel2_case1;
    private javax.swing.JLabel jLabel2_nbrdetentatives;
    private javax.swing.JLabel jLabel3_afficherhauts;
    private javax.swing.JLabel jLabel3_case2;
    private javax.swing.JLabel jLabel4_afficherbas;
    private javax.swing.JLabel jLabel4_case3;
    private javax.swing.JLabel jLabel5_case4;
    private javax.swing.JLabel jLabel6_tentatives;
    private javax.swing.JLabel jLabel7_exact;
    private javax.swing.JLabel jLabel8_hauts;
    private javax.swing.JLabel jLabel9_bas;
    // End of variables declaration//GEN-END:variables
}
