/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FenetreQuiz;

import java.util.ArrayList;



/**
 *
 * @author emirb
 */
public class FenetreQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());
private ArrayList<Questions> listeQuestions = new ArrayList<>();
private int indexQuestionCourante = 0;
private int score = 0;
    /**
     * Creates new form FenetreQuiz
     */

    private void afficherQuestionCourante() {
    Questions q = listeQuestions.get(indexQuestionCourante);

    jLabel_question.setText(q.getIntitule());
    jButton_Rep1.setText(q.getProposition1());
    jButton_Rep2.setText(q.getProposition2());
    jButton_Rep3.setText(q.getProposition3());
    jButton_Rep4.setText(q.getProposition4());

    jLabel_resultat.setText(""); // Réinitialise le feedback

    // Réactive les boutons
    jButton_Rep1.setEnabled(true);
    jButton_Rep2.setEnabled(true);
    jButton_Rep3.setEnabled(true);
    jButton_Rep4.setEnabled(true);
}
    private void traiterReponse(int numChoisi) {
    Questions Q1 = listeQuestions.get(indexQuestionCourante);

    if (numChoisi == Q1.getIndexBonneReponse()) {
        jLabel_resultat.setText("Bonne réponse !");
        score++;
        jLabel_score.setText("Score : " + score);
    } else {
        jLabel_resultat.setText("Mauvaise réponse !");
    }

    // Désactivation des 4 boutons
    jButton_Rep1.setEnabled(false);
    jButton_Rep2.setEnabled(false);
    jButton_Rep3.setEnabled(false);
    jButton_Rep4.setEnabled(false);

}
    
    public FenetreQuiz() {
        initComponents();
        
    listeQuestions.add(new Questions("La couleur du cœur dans un jeu de cartes",
                                 "Blanc", "Vert", "Noir", "Rouge", 4));

    listeQuestions.add(new Questions("Combien de point sur une ligne ?",
                                 "1", "Impossible de le savoir", "Aucune idee", "2", 2));

    listeQuestions.add(new Questions("Capitale de la Turquie?",
                                 "Istanbul", "Kars", "Ankara", "Sivas", 3));

    listeQuestions.add(new Questions("Le plus grand continent ?",
                                 "Europe", "Asie", "Amerique", "Afrique", 4));

    listeQuestions.add(new Questions("Le jour apres Lundi ?",
                                 "Vendrei", "Vendredi", "Vendredie", "Vandredi", 2));

// Affiche la première question
afficherQuestionCourante();


    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The c      ontent of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_question = new javax.swing.JLabel();
        jButton_Rep1 = new javax.swing.JButton();
        jButton_Rep2 = new javax.swing.JButton();
        jButton_Rep3 = new javax.swing.JButton();
        jButton_Rep4 = new javax.swing.JButton();
        jLabel_resultat = new javax.swing.JLabel();
        jButton_questionsuivante = new javax.swing.JButton();
        jLabel_score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_question.setText("lblQuestion");
        jLabel_question.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel_questionFocusGained(evt);
            }
        });

        jButton_Rep1.setText("Rep1");
        jButton_Rep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Rep1ActionPerformed(evt);
            }
        });

        jButton_Rep2.setText("Rep2");
        jButton_Rep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Rep2ActionPerformed(evt);
            }
        });

        jButton_Rep3.setText("Rep3");
        jButton_Rep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Rep3ActionPerformed(evt);
            }
        });

        jButton_Rep4.setText("Rep4");
        jButton_Rep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Rep4ActionPerformed(evt);
            }
        });

        jLabel_resultat.setText("jLabel_resu");

        jButton_questionsuivante.setText("question suivante ");
        jButton_questionsuivante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_questionsuivanteActionPerformed(evt);
            }
        });

        jLabel_score.setText("score");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Rep3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Rep1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Rep2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Rep4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel_question, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_score, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jButton_questionsuivante, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel_resultat, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_question, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel_score, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel_resultat)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Rep1)
                    .addComponent(jButton_Rep2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton_Rep3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton_Rep4)))
                .addGap(30, 30, 30)
                .addComponent(jButton_questionsuivante, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Rep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Rep3ActionPerformed
        // TODO add your handling code here:
        traiterReponse(3);
        
                
    }//GEN-LAST:event_jButton_Rep3ActionPerformed

    private void jButton_Rep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Rep1ActionPerformed
        // TODO add your handling code here:
        traiterReponse(1);
    }//GEN-LAST:event_jButton_Rep1ActionPerformed

    private void jButton_Rep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Rep4ActionPerformed
        // TODO add your handling code here:
        traiterReponse(4);
    }//GEN-LAST:event_jButton_Rep4ActionPerformed
        
    private void jButton_Rep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Rep2ActionPerformed
        // TODO add your handling code here:
        traiterReponse(2);
    }//GEN-LAST:event_jButton_Rep2ActionPerformed
        
    private void jLabel_questionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel_questionFocusGained
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jLabel_questionFocusGained

    private void jButton_questionsuivanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_questionsuivanteActionPerformed
                                                             

    indexQuestionCourante++;

    if (indexQuestionCourante < listeQuestions.size()) {

        afficherQuestionCourante();

        // Mise à jour en temps réel du score
        jLabel_score.setText("Score : " + score);

    } else {

        jLabel_question.setText("Quiz terminé !");
        jLabel_resultat.setText("Score final : " + score + " / " + listeQuestions.size());

        // Désactiver tous les boutons
        jButton_questionsuivante.setEnabled(false);
        jButton_Rep1.setEnabled(false);
        jButton_Rep2.setEnabled(false);
        jButton_Rep3.setEnabled(false);
        jButton_Rep4.setEnabled(false);
    }


    }//GEN-LAST:event_jButton_questionsuivanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Rep1;
    private javax.swing.JButton jButton_Rep2;
    private javax.swing.JButton jButton_Rep3;
    private javax.swing.JButton jButton_Rep4;
    private javax.swing.JButton jButton_questionsuivante;
    private javax.swing.JLabel jLabel_question;
    private javax.swing.JLabel jLabel_resultat;
    private javax.swing.JLabel jLabel_score;
    // End of variables declaration//GEN-END:variables

}