/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FenetreQuiz;

/**
 *
 * @author emirb
 */
public class FenetreQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    /**
     * Creates new form FenetreQuiz
     */
     Questions Q1 ;
    
    public FenetreQuiz() {
        initComponents();
        
       Q1 = new Questions("La couleur du coeur dans un jeux de cartes","Blancs","Verts","Noir","Rouge",4);
       jLabel_question.setText(Q1.getIntitule());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_question = new javax.swing.JLabel();
        jButton_Rep1 = new javax.swing.JButton();
        jButton_Rep2 = new javax.swing.JButton();
        jButton_Rep3 = new javax.swing.JButton();
        jButton_Rep4 = new javax.swing.JButton();
        jLabel_resultat = new javax.swing.JLabel();
        jButton_questionsuivante = new javax.swing.JButton();
        jLabel_score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_question.setText("lblQuestion");
        jLabel_question.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel_questionFocusGained(evt);
            }
        });

        jButton_Rep1.setText("Rep1");
        jButton_Rep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Rep1ActionPerformed(evt);
            }
        });

        jButton_Rep2.setText("Rep2");
        jButton_Rep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Rep2ActionPerformed(evt);
            }
        });

        jButton_Rep3.setText("Rep3");
        jButton_Rep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Rep3ActionPerformed(evt);
            }
        });

        jButton_Rep4.setText("Rep4");
        jButton_Rep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Rep4ActionPerformed(evt);
            }
        });

        jLabel_resultat.setText("jLabel_resu");

        jButton_questionsuivante.setText("qsuivante");

        jLabel_score.setText("score");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Rep3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Rep1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Rep2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Rep4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel_resultat, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_questionsuivante, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_question, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                                .addComponent(jLabel_score, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_question, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel_score)))
                .addGap(18, 18, 18)
                .addComponent(jLabel_resultat)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Rep1)
                    .addComponent(jButton_Rep2))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Rep3)
                    .addComponent(jButton_Rep4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_questionsuivante)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Rep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Rep3ActionPerformed
        // TODO add your handling code here:
        jButton_Rep1.setText(Q1.getProposition3());
    }//GEN-LAST:event_jButton_Rep3ActionPerformed

    private void jButton_Rep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Rep1ActionPerformed
        // TODO add your handling code here:
        jButton_Rep1.setText(Q1.getProposition1());
    }//GEN-LAST:event_jButton_Rep1ActionPerformed

    private void jButton_Rep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Rep4ActionPerformed
        // TODO add your handling code here:
        jButton_Rep1.setText(Q1.getProposition4());
    }//GEN-LAST:event_jButton_Rep4ActionPerformed

    private void jButton_Rep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Rep2ActionPerformed
        // TODO add your handling code here:
        jButton_Rep1.setText(Q1.getProposition2());
    }//GEN-LAST:event_jButton_Rep2ActionPerformed

    private void jLabel_questionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel_questionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_questionFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Rep1;
    private javax.swing.JButton jButton_Rep2;
    private javax.swing.JButton jButton_Rep3;
    private javax.swing.JButton jButton_Rep4;
    private javax.swing.JButton jButton_questionsuivante;
    private javax.swing.JLabel jLabel_question;
    private javax.swing.JLabel jLabel_resultat;
    private javax.swing.JLabel jLabel_score;
    // End of variables declaration//GEN-END:variables
}
